// <auto-generated />
using System;
using Evently.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Evently.Infrastructure.Migrations
{
    [DbContext(typeof(EventlyDbContext))]
    partial class EventlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Evently.Domain.EventAggregate.Event", b =>
                {
                    b.Property<Guid>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ScheduledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 11, 26, 0, 4, 1, 356, DateTimeKind.Utc).AddTicks(5168));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEvent");

                    b.HasIndex("Title");

                    b.ToTable("Events", "EMain", t =>
                        {
                            t.HasCheckConstraint("CK_Event_Capacity_Positive", "[Capacity] >= 0");
                        });
                });

            modelBuilder.Entity("Evently.Domain.RegistrationAggregate.Registration", b =>
                {
                    b.Property<Guid>("IdRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 11, 26, 0, 4, 1, 357, DateTimeKind.Utc).AddTicks(7634));

                    b.HasKey("IdRegistration");

                    b.HasIndex("EventId", "Email")
                        .IsUnique();

                    b.ToTable("Registrations", "EMain");
                });

            modelBuilder.Entity("Evently.Infrastructure.Persistance.OutboxMessage", b =>
                {
                    b.Property<Guid>("IdOutboxMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdOutboxMessage");

                    b.ToTable("OutboxMessages", "EMain");
                });

            modelBuilder.Entity("Evently.Infrastructure.ReadModels.EventReadModel", b =>
                {
                    b.Property<Guid>("IdReadModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdReadModel");

                    b.ToTable("EntityReadModels", "EMain");
                });
#pragma warning restore 612, 618
        }
    }
}
